name: Main
on: [push]
jobs:
  build-flutter-engine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.x
      uses: actions/setup-python@v2
      with:
        python-version: '2.x'
    - name: Prepare Env
      run: |
        sudo apt-get update
        sudo apt-get install g++-aarch64-linux-gnu
        sudo apt-get install g++-multilib
        sudo apt-get install zip
    - name: Get Resource
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        export PATH="$PATH:$PWD/depot_tools"
        mkdir flutter-engine
        echo 'solutions = [
        {
         "managed": False,
         "name": "src/flutter",
         "url": "https://github.com/flutter/engine",
         "custom_deps": {},
         "deps_file": "DEPS",
         "safesync_url": "",
        },
        ]' >> flutter-engine/.gclient
        cd flutter-engine
        gclient sync
    - name: Build Engine
      run: |
        export PATH="$PATH:$PWD/depot_tools"
        cd flutter-engine/src
        ls flutter/
        ls flutter/tools
        ./flutter/tools/gn --target-os linux --linux-cpu arm64 --runtime-mode release
        ninja -C out/linux_release_arm64
        ./flutter/tools/gn --target-os linux --linux-cpu arm64 --runtime-mode debug
        ninja -C out/linux_debug_arm64
    - name: Zip Engine
      run: |
        cd flutter-engine/src
        zip -q -r linux_release_arm64.zip out/linux_release_arm64
        zip -q -r linux_debug_arm64.zip out/linux_debug_arm64
    - name: Release Engine
      uses: ncipollo/release-action@v1.5.0
      with:
        artifacts: "flutter-engine/src/*.zip"
        tag: "linux_arm64"
        token: ${{ secrets.RELEASE_TOKEN }}
